#!/bin/bash

echo "=====================================" >> jugadores.res
echo >> jugadores.res
echo "With heuristics" >> jugadores.res
cat heuristics.cl | grep -v ";" >> jugadores.res
echo >> jugadores.res
echo "Results" >> jugadores.res
cat results.dat >> jugadores.res
echo >> jugadores.res

if [ -z $1 ]; then
	cat >> jugadores.res
fi
